//go:build ignore

package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/jackc/pgx/v5"
	_ "github.com/jackc/pgx/v5/stdlib"
)

func main() {
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		fmt.Println("DATABASE_URL environment variable not set")
		os.Exit(1)
	}

	ctx := context.Background()
	conn, err := pgx.Connect(ctx, dbURL)
	if err != nil {
		fmt.Printf("Failed to connect: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(ctx)

	fmt.Println("-- Database Dump")
	fmt.Println("-- Generated by dump_db.go")
	fmt.Printf("-- Database: %s\n\n", extractDatabaseName(dbURL))

	// Get all tables except system tables
	tables, err := getTables(ctx, conn)
	if err != nil {
		fmt.Printf("Error getting tables: %v\n", err)
		os.Exit(1)
	}

	// Dump schema for each table
	for _, table := range tables {
		if err := dumpTableSchema(ctx, conn, table); err != nil {
			fmt.Printf("Error dumping schema for %s: %v\n", table, err)
		}
	}

	// Dump data for each table
	for _, table := range tables {
		if err := dumpTableData(ctx, conn, table); err != nil {
			fmt.Printf("Error dumping data for %s: %v\n", table, err)
		}
	}
}

func extractDatabaseName(dbURL string) string {
	parts := strings.Split(dbURL, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "unknown"
}

func getTables(ctx context.Context, conn *pgx.Conn) ([]string, error) {
	rows, err := conn.Query(ctx, `
		SELECT table_name
		FROM information_schema.tables
		WHERE table_schema = 'public'
		AND table_type = 'BASE TABLE'
		ORDER BY table_name
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var table string
		if err := rows.Scan(&table); err != nil {
			return nil, err
		}
		tables = append(tables, table)
	}
	return tables, nil
}

func dumpTableSchema(ctx context.Context, conn *pgx.Conn, table string) error {
	// Get CREATE TABLE statement
	fmt.Printf("-- Schema for table: %s\n", table)
	fmt.Printf("DROP TABLE IF EXISTS %s CASCADE;\n", quoteIdentifier(table))

	// Get columns
	rows, err := conn.Query(ctx, `
		SELECT
			column_name,
			data_type,
			is_nullable,
			column_default,
			character_maximum_length,
			numeric_precision,
			numeric_scale
		FROM information_schema.columns
		WHERE table_name = $1
		AND table_schema = 'public'
		ORDER BY ordinal_position
	`, table)
	if err != nil {
		return err
	}
	defer rows.Close()

	var columns []struct {
		Name             string
		Type             string
		Nullable         string
		Default          *string
		CharMaxLen       *int
		NumericPrecision *int
		NumericScale     *int
	}

	for rows.Next() {
		var col struct {
			Name             string
			Type             string
			Nullable         string
			Default          *string
			CharMaxLen       *int
			NumericPrecision *int
			NumericScale     *int
		}
		if err := rows.Scan(&col.Name, &col.Type, &col.Nullable, &col.Default, &col.CharMaxLen, &col.NumericPrecision, &col.NumericScale); err != nil {
			return err
		}
		columns = append(columns, col)
	}

	fmt.Printf("CREATE TABLE %s (\n", quoteIdentifier(table))
	for i, col := range columns {
		colDef := fmt.Sprintf("    %s %s", quoteIdentifier(col.Name), getColumnType(col))
		if col.Nullable == "NO" {
			colDef += " NOT NULL"
		}
		if col.Default != nil {
			colDef += fmt.Sprintf(" DEFAULT %s", *col.Default)
		}
		if i < len(columns)-1 {
			colDef += ","
		}
		fmt.Println(colDef)
	}
	fmt.Println(");")
	fmt.Println()

	return nil
}

func getColumnType(col struct {
	Name             string
	Type             string
	Nullable         string
	Default          *string
	CharMaxLen       *int
	NumericPrecision *int
	NumericScale     *int
}) string {
	switch col.Type {
	case "character varying":
		if col.CharMaxLen != nil && *col.CharMaxLen > 0 {
			return fmt.Sprintf("VARCHAR(%d)", *col.CharMaxLen)
		}
		return "VARCHAR"
	case "text":
		return "TEXT"
	case "integer":
		return "INTEGER"
	case "bigint":
		return "BIGINT"
	case "smallint":
		return "SMALLINT"
	case "numeric", "decimal":
		if col.NumericPrecision != nil && col.NumericScale != nil {
			return fmt.Sprintf("NUMERIC(%d,%d)", *col.NumericPrecision, *col.NumericScale)
		}
		return "NUMERIC"
	case "boolean":
		return "BOOLEAN"
	case "timestamp with time zone":
		return "TIMESTAMPTZ"
	case "timestamp without time zone":
		return "TIMESTAMP"
	case "date":
		return "DATE"
	case "json", "jsonb":
		return col.Type
	case "uuid":
		return "UUID"
	case "ARRAY":
		return "TEXT[]" // Simplified
	default:
		return "TEXT"
	}
}

func dumpTableData(ctx context.Context, conn *pgx.Conn, table string) error {
	// Check if table has data
	var count int
	if err := conn.QueryRow(ctx, fmt.Sprintf("SELECT COUNT(*) FROM %s", quoteIdentifier(table))).Scan(&count); err != nil {
		return err
	}

	if count == 0 {
		fmt.Printf("-- No data in %s\n\n", table)
		return nil
	}

	fmt.Printf("-- Data for table: %s (%d rows)\n", table, count)

	rows, err := conn.Query(ctx, fmt.Sprintf("SELECT * FROM %s", quoteIdentifier(table)))
	if err != nil {
		return err
	}
	defer rows.Close()

	fieldDescriptions := rows.FieldDescriptions()
	columnNames := make([]string, len(fieldDescriptions))
	for i, fd := range fieldDescriptions {
		columnNames[i] = string(fd.Name)
	}

	for rows.Next() {
		values, err := rows.Values()
		if err != nil {
			return err
		}

		valueStrings := make([]string, len(values))
		for i, v := range values {
			valueStrings[i] = formatValue(v)
		}

		fmt.Printf("INSERT INTO %s (%s) VALUES (%s);\n",
			quoteIdentifier(table),
			strings.Join(quoteIdentifiers(columnNames), ", "),
			strings.Join(valueStrings, ", "))
	}

	fmt.Println()
	return nil
}

func formatValue(v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case string:
		// Escape single quotes
		escaped := strings.ReplaceAll(val, "'", "''")
		return "'" + escaped + "'"
	case []byte:
		escaped := strings.ReplaceAll(string(val), "'", "''")
		return "'" + escaped + "'"
	case bool:
		if val {
			return "TRUE"
		}
		return "FALSE"
	default:
		return fmt.Sprintf("%v", v)
	}
}

func quoteIdentifier(id string) string {
	// PostgreSQL quotes identifiers with double quotes
	return `"` + strings.ReplaceAll(id, `"`, `""`) + `"`
}

func quoteIdentifiers(ids []string) []string {
	result := make([]string, len(ids))
	for i, id := range ids {
		result[i] = quoteIdentifier(id)
	}
	return result
}
